# TODO: Add Hackage fields
name: shrtn
version: 0.1.0.0

# TODO: turn on -Werror after some development
ghc-options: -Wall -O2

dependencies:
  - aeson < 1.3
  - async < 2.2
  - base >= 4.7 && < 5
  - bytestring < 0.11
  - data-default < 0.8
  - directory < 1.4
  - http-api-data < 0.4
  - http-types < 0.10
  - lucid < 2.10
  - random < 1.2
  - servant < 0.12
  - servant-server < 0.12
  - stm < 2.5
  - text < 1.3
  - unordered-containers < 0.3
  - wai < 3.3
  - wai-extra < 3.1
  - warp < 3.3

library:
  source-dirs: src

executables:
  shrtn:
    source-dirs: app
    main: Main.hs
    dependencies:
      - shrtn
